config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'static_pages/about'

  resources :users
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, presence: true

	has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
validates :title, :description, presence: true
belongs_to :category
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


  def index
    @categories = Category.all
  end

  def new
  	@category = Category.new
  end

  def create
  	@category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category created successfuly."
      redirect_to @category
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:success] = "Updated successfuly."
      redirect_to @category
    else
      render 'new'
    end
  end

  def destroy
    @category = Category.find(params[:id]).destroy
    flash[:danger] = "Deleted successfuly."
    redirect_to @category
  end

  private

  def category_params
  	params.require(:category).permit(:name)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  end

  def index
  	@users = User.all
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "You have successfuly posted your thought."
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def show
  	@user = User.find(params[:id])
  end


  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update_attributes(user_params)
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def destroy
  	@user = User.find(params[:id]).destroy
  	flash[:danger] = "You have deleted User."
  	redirect_to users_url
  end

  private
  	def user_params
  		params.require(:user).permit(:title, :description, :category_id)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
Category: <%= link_to category.name, category %><br>

app/views/categories/_form.html.erb
<div class = "container">
<%= simple_form_for(@category) do |f| %>



<div class="row">
<div class="col-xs-8">
		<%= f.label :Category %>
		<%= f.text_field :name %>
	</div><br>
</div>

	<div class="row">
	<div class="col-xs-8">
  <div class="form-actions">
    <%= f.button :submit, "post",	 class: "btn btn-success" %>
  </div>
</div>
</div>
  <br />

</div>
</div>

<% end %>

app/views/categories/edit.html.erb
<h2>Update Your Category Here....</h2>

<%= render 'form' %>

<%= link_to 'back', categories_path	%>

app/views/categories/index.html.erb
<h2>See all categories.</h2>

<%= render @categories %>

app/views/categories/new.html.erb
<h2>Add Category Here....</h2>

<%= render 'form' %>

<%= link_to 'show', @category %>

app/views/categories/show.html.erb
<h2>List of categories.</h2>
Category: <%= @category.name %>
<br>

<%= render @category.users %>

<%= link_to 'delete', @category, method: :delete, data: { confirm: "You sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <title>KnowMore</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/header' %>
<div class="container">
    <% flash.each do |msg_type,msg| %>
   <!-- <div class = "alert alert-<%= msg_type %>"><%= msg %> </div> -->
    <%= content_tag(:div, msg, class: "alert alert-#{msg_type}") %> 
    <% end %>
</div>
<%= yield %>
<%= render 'shared/footer' %>

</body>
</html>

app/views/shared/_error_message.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
    <div class="alert alert-danger">
        This form contains <%= pluralize(@user.errors.count, "Error") %>
    </div>
    <ul>
        <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <ul class="nav nav-pills pull-right">
      <li role="presentation"><a href="#">Home</a></li>
       <li role="presentation"><a href="#">Category</a></li>
      <li role="presentation"><a href="#">About</a></li>
      <li role="presentation"><a href="<%= new_user_path %>">Put Thought</a></li>
      <li role="presentation"><a href="<%= new_category_path %>">Category</a></li>
       </div>
       </nav> 

 <!-- <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="#">Home</a></li>
            <li role="presentation"><a href="#"><b>Add Movie Review</b></a></li>
            <li role="presentation"><a href="#"><b>See Movie's Review</b> </a></li>
          </ul>
        </nav>
        </div> -->

<!-- <nav class="navbar navbar-default navbar-static-top">
  <div class="container">
<ul class="nav nav-pills pull-right">
  <li role="presentation" class="active"><a href="#">Home</a></li>
  <li role="presentation"><a href="#">About</a></li>
  <li role="presentation"><a href="#">Category</a></li>
</ul>
</div>
</nav> -->

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/_form.html.erb
<div class = "container">
<%= simple_form_for(@user) do |f| %>

<%= render 'shared/error_message' %>

<div class="row">
<div class="col-xs-8">
		<%= f.label :Question %>
		<%= f.text_field :title %>
	</div><br>
</div>

<div class="row">
	<div class="col-xs-8">
		<br>
		<%= f.label :Answer %>
		<%= f.text_area :description %>
	</div>

<div class="row">
  <div class="col-xs-4">
    <%= f.association :category, include_blank: false %>
  </div>
</div>

	<div class="row">
	<div class="col-xs-8">
  <div class="form-actions">
    <%= f.button :submit, "post",	 class: "btn btn-success" %>
  </div>
</div>
</div>
  <br />

</div>
</div>

<% end %>

app/views/users/_user.html.erb
<br>Question: <%= link_to user.title, user %>
<br>
Answer: <%= user.description %>

app/views/users/edit.html.erb
<h2>Update your thought here....</h2>

<%= render 'form' %>

<%= link_to 'back', users_path %>

app/views/users/index.html.erb
<h2>Here is list of all users thoughts.</h2>

<!--<% @users.each do |user| %>

<%= link_to user.title, user %>
<%= user.description %>

<% end %> -->

<%= render @users %>

app/views/users/new.html.erb
<h2>Put Your thought</h2>
<p>Share Your knowledge</p>

<%= render 'form' %>

<%= link_to 'show', users_path %>

app/views/users/show.html.erb
Question: <%= @user.title %>
<br>
Answer: <%= @user.description %>
<br>

<%= link_to 'delete', @user, method: :delete, data: { confirm: 'Are you sure?'} %> |
<%= link_to 'edit', edit_user_path(@user) %>